version: '3'
services:
  crypto-currency-watcher:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - ${APP_PORT}:8080
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432